pipeline {
    agent { docker { image 'node:6.3' } }

    stages {
        stage('Build') {
            steps {
                sh 'npm run build-prod'
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'npm run test'
            }
        }
    }
}